### ISSUE TITLE
adding concenated effect to layer c3 crashes

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#1]
source Effects:
Mikal BigBlurV
Mikal BigBlurH

when I add the concenated effects to a layer c3 Crashes:
[Mikal_BigBlurV_Mikal_BigBlurH.zip](https://github.com/ConstructFund/c3-effects-concat/files/8958765/Mikal_BigBlurV_Mikal_BigBlurH.zip)
**it's concenated effect with a .zip ending to upload it. Not zipped**

Error report information
Type: unhandled exception
File: https://editor.construct.net/r299/main.js, line 1991, col 319
Message: Uncaught Error: effect shader program not compiled
Stack: Error: effect shader program not compiled at d.d3 (https://editor.construct.net/r299/main.js:1991:325) at https://editor.construct.net/r299/projectResources.js:1272:213 at Array.map () at d.cHa (https://editor.construct.net/r299/projectResources.js:1272:199) at d.tU (https://editor.construct.net/r299/projectResources.js:1271:469) at d.Gf (https://editor.construct.net/r299/projectResources.js:1274:210) at d.Gf (https://editor.construct.net/r299/projectResources.js:1233:3) at a_b (https://editor.construct.net/r299/components/editors/layoutView/layoutView.js:78:153)
Construct version: r299
URL: https://editor.construct.net/r299/
Date: Wed Jun 22 2022 16:43:44 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 12.2 s

Platform information
Product: Construct 3 r299 (beta)
Browser: Chrome 103.0.5060.53
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by skymen** [comment]
Thanks for the report this should be fixed along with
https://github.com/ConstructFund/c3-effects-concat/issues/3

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/175342937-eca4ef05-fe98-4d7e-86f4-e855b85dff19.png)
Fixed in next release (I'll upload it today)

**Comment by skymen** [comment]
released
