### ISSUE TITLE
allow adding the same effect multiple times

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#10]
I am trying to create a color pallete swapper, using multiple replaceColor effects.
Sadly concat only allows adding each effect once.

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/175390795-b30d51c0-b454-4beb-8911-0f8427299e4e.png)
Added in next release (might not work 100% so please test it when it comes out)

**Comment by skymen** [comment]
Try with new release please
