### ISSUE TITLE
betterOutline+DropShadow crash when applying to layer

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#11]
Construct crashes when adding the concat effect of betterOutline+DropShadow to a layer

**Comment by skymen** [comment]
Can you send a link to DropShadow?

Is it this one? https://www.construct.net/en/make-games/addons/92/drop-shadow

on my end, this one wouldn't even export

**Comment by F3der1co** [comment]
the one I used says Author Skymen, idk where I had it from.
Checked and it's your [Colored Drop Shadow](https://www.construct.net/en/make-games/addons/540/colored-drop-shadow) I think, but only says DropShadow in Construct.

**Comment by skymen** [comment]
Alright, thanks I found the issue, will be in next release

**Comment by skymen** [comment]
pushed release
