### ISSUE TITLE
(minor/unimportant) transition from dark to light mode looks awkward

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#15]
I think it's awesome to have a light and dark mode, but I feel like the transition is a bit awkward.
Certain parts have a smooth transition others switch instantly, leading to the transition period looking kinda messy.

I would rather have a unified smooth transition or have all switch color instantly.

**Comment by skymen** [comment]
Can you check now? I think this was a css oversight on my end

**Comment by F3der1co** [comment]
much better now :)

**Comment by skymen** [comment]
Nice
