### ISSUE TITLE
Provide default c3 fxs

### ISSUE THREAD

**Issue by mitsuhashish** [ConstructFund/c3-effects-concat#2]
I'd like to propose/request the addition of default c3 fxs so that only 3rd part will need to be uploaded

**Comment by skymen** [comment]
Fixed in next release (will be uploladed today)
![image](https://user-images.githubusercontent.com/11213825/175343139-de499553-1f6a-49e0-936f-e6b330383efc.png)

**Comment by skymen** [comment]
released
