### ISSUE TITLE
merge dublicated authors and allow setting custom name

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#7]
with the concat effects, the names and description can get extremely long. 
It would be nice if the user can set a custom name.
Secondly instead of having Multiple Scirras as author it would be cool to have it automatically remove dublicates.

Only downside of this would be that which author did which effect will not be clear anymore.

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/175363935-46fc9742-78e4-4462-8a9c-131e56fd8080.png)
Added

**Comment by F3der1co** [comment]
awesome!

**Comment by skymen** [comment]
Test with new release please
