### ISSUE TITLE
error when trying to concat

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#8]
I was trying to create a retro-screen effect-stack (Noise+ScanLines+Sphere) but they gave me errors.

I found Noise gives error:
TypeError: Cannot read properties of undefined (reading 'type')

and Sphere:
TypeError: Cannot read properties of undefined (reading 'scope')

**Comment by skymen** [comment]
Should be fixed with https://github.com/ConstructFund/c3-effects-concat/issues/5

**Comment by skymen** [comment]
should be fixed with release 3
