### ISSUE TITLE
add a warning to effects that are likely to perform worse when concat

### ISSUE THREAD

**Issue by F3der1co** [ConstructFund/c3-effects-concat#9]
I'm imagining something like an red exclaimation mark icon next to the effects in the list of vanilla ones. 

This would be helpful so the user doesn't have to test so much.
Downside is that this might require thoroughly testing effects and also requires some maintance when effects are found to perform worse.

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/175390644-2e50962d-41a6-42e0-a72a-474b17234f16.png)
Added in next release

**Comment by skymen** [comment]
try with new release. For now, I marked the ones with more than 5 texture reads. Let me know if you find other cases where there is an issue, or effects that are marked as problematic and actually are not
